### ISSUE TITLE
About updates

### ISSUE THREAD

**Issue by kakawlala** [WantClue/bitaxe-web-flasher#1]
Hi，About updates

bitaxeUltra205 has been launched, will updates be provided“esp-miner-factory-205-v2.0.7.bin”？
[https://github.com/skot/bitaxe/releases/tag/205](url)

Will Bitaxe Web installer update the function to respond to Bitaxe supra (V400 BM1368PB asic)?
[https://github.com/skot/bitaxe/releases/tag/v400-order](url)

I'm not good at using "bitaxetool", Bitaxe Web installer helped me a lot.

**Comment by WantClue** [comment]
The 205 version will follow soon on the web flasher
